[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = true

[fmt]
line_length = 100
multiline_func_header = "attributes_first"
