name: ci
on:
  push:
  pull_request:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: node -v && npm -v
      - name: List
        run: ls -la && echo "OK ✅"
