name: ci
on:
  push:
  pull_request:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show tree
        run: |
          echo "Repo structure:"
          ls -la
          echo "OK ✅"
